name: Nightly Tests

on:
  schedule:
    - cron: '0 2 * * *'

  workflow_dispatch:

jobs:
  nightly-regression:
    name: Nightly Full Regression

    permissions:
      contents: read
      checks: write

    uses: ./.github/workflows/reusable-test-run.yml
    with:
      groups: full-regression
      exclude_quarantine: true
      allow_failure: false

  quarantine-tests:
    name: Quarantine Tests

    permissions:
      contents: read
      checks: write

    uses: ./.github/workflows/reusable-test-run.yml
    with:
      groups: quarantine
      exclude_quarantine: false
      allow_failure: true